#ifndef __CONSTANTS_H_
#define __CONSTANTS_H_

// Scene id
typedef enum
{
	SCENE_ID_NONE = -1,
	SCENE_ID_MAINMENU,
	SCENE_ID_PLAY,
	SCENE_ID_SETTINGS,
	SCENE_ID_ABOUT,
	SCENE_ID_RESULTS,
	SCENE_ID_RESTART,
	SCENE_ID_QUIT
} SCENE_ID;

// Main menu id
typedef enum
{
	MAINMENU_ID_NONE = -1,
	MAINMENU_ID_START,
	MAINMENU_ID_SETTING,
	MAINMENU_ID_ABOUT,
	MAINMENU_ID_QUIT
} MAINMENU_ID;

// Character states
typedef enum
{
	CHAR_STATE_NONE = -1,
	CHAR_STATE_SPAWN,
	CHAR_STATE_SHOOT,
	CHAR_STATE_DEAD
} CHAR_STATE;

typedef enum
{
	TYPE_ID_NONE = -1,
	TYPE_ID_PLAYER,
	TYPE_ID_ENEMY,
	TYPE_ID_BG
} TYPE_ID;

typedef enum
{
	RESTART_ID_NONE = -1,
	RESTART_ID_YES,
	RESTART_ID_NO
} RESTART_ID;

typedef enum
{
	TRANSITION_ID_NONE = -1,
	TRANSITION_ID_JUMPZOOM,
	TRANSITION_ID_PROGRESSRADIALCCW,
	TRANSITION_ID_PROGRESSRADIALCW,
	TRANSITION_ID_HORIZONTAL,
	TRANSITION_ID_VERTICAL,
	TRANSITION_ID_INOUT,
	TRANSITION_ID_OUTIN,
	TRANSITION_ID_CROSSFADE,
	TRANSITION_ID_PAGETRANSITIONFORWARD,
	TRANSITION_ID_PAGETRANSITIONBACKWARD,
	TRANSITION_ID_FADETR,
	TRANSITION_ID_FADEBL,
	TRANSITION_ID_FADEUP,
	TRANSITION_ID_FADEDOWN,
	TRANSITION_ID_TURNOFFTILES,
	TRANSITION_ID_SPLITROWS,
	TRANSITION_ID_SPLITCOLS,
	TRANSITION_ID_FADE,
	TRANSITION_ID_FADEWHITETRANSITION,
	TRANSITION_ID_FLIPXLEFTOVER,
	TRANSITION_ID_FLIPXRIGHTOVER,
	TRANSITION_ID_FLIPYUPOVER,
	TRANSITION_ID_FLIPYDOWNOVER,
	TRANSITION_ID_FLIPANGULARLEFTOVER,
	TRANSITION_ID_FLIPANGULARRIGHTOVER,
	TRANSITION_ID_ZOOMFLIPXLEFTOVER,
	TRANSITION_ID_ZOOMFLIPXRIGHTOVER,
	TRANSITION_ID_ZOOMFLIPYUPOVER,
	TRANSITION_ID_ZOOMFLIPYDOWNOVER,
	TRANSITION_ID_ZOOMFLIPANGULARLEFTOVER,
	TRANSITION_ID_ZOOMFLIPANGULARRIGHTOVER,
	TRANSITION_ID_SHRINKGROW,
	TRANSITION_ID_ROTOZOOM,
	TRANSITION_ID_MOVEINL,
	TRANSITION_ID_MOVEINR,
	TRANSITION_ID_MOVEINT,
	TRANSITION_ID_MOVEINB,
	TRANSITION_ID_SLIDEINL,
	TRANSITION_ID_SLIDEINR,
	TRANSITION_ID_SLIDEINT,
	TRANSITION_ID_SLIDEINB

} TRANSITION_ID;


#endif